language: objective-c
os: osx
osx_image: xcode9.3

xcode_project: Bergjes2018.xcodeproj
xcode_scheme: Bergjes2018

before_install:
 - pod repo update

script:
    - xcodebuild clean build -sdk iphonesimulator -workspace Bergjes2018.xcworkspace -scheme Bergjes2018Tests CODE_SIGNING_REQUIRED=NO
