language: objective-c
os: osx
osx_image: xcode9.3

xcode_project: Bergjes2018.xcodeproj
xcode_scheme: Bergjes2018

addons:
  sonarcloud:
    organization: "spark404-github"

before_install:
 - pod repo update
 - gem install xcpretty

script:
    - set -o pipefail && xcodebuild  -scheme Bergjes2018 -sdk iphonesimulator11.3 -workspace Bergjes2018.xcworkspace  -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.3' CODE_SIGNING_REQUIRED=NO test | xcpretty
    - sonar-scanner
